# Generated by Django 4.2.9 on 2024-02-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_comment_post"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="author",),
        migrations.AddField(
            model_name="post", name="slug", field=models.SlugField(default=""),
        ),
    ]
