# Generated by Django 4.2.9 on 2024-02-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="", editable=False),
        ),
    ]
