# Generated by Django 4.2.9 on 2024-02-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="posted", field=models.DateField(auto_now=True),
        ),
    ]
