# Generated by Django 4.2.9 on 2024-02-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(model_name="author", name="address",),
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
