# Generated by Django 4.2.9 on 2024-02-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_tag_remove_author_address_author_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(related_name="posts", to="posts.tag"),
        ),
    ]
