# Generated by Django 4.2.9 on 2024-02-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_remove_post_tag_post_excerpt_post_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="posts"),
        ),
    ]
