# Generated by Django 5.0.1 on 2024-02-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=300),
        ),
    ]
