# Generated by Django 5.0.1 on 2024-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_alter_comment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="image",
            field=models.ImageField(null=True, upload_to="posts"),
        ),
    ]
