# Generated by Django 5.0.1 on 2024-02-24 10:49

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0015_rename_content_post_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="post",
            name="body",
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=None, verbose_name="Text"
            ),
        ),
    ]
