# Generated by Django 5.0.1 on 2024-02-24 11:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0016_remove_comment_email_remove_post_body_post_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.AddField(
            model_name="post",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=""),
        ),
    ]
