# Generated by Django 5.0.1 on 2024-02-24 11:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0017_remove_post_content_post_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="body",
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default="Hello world Django!", verbose_name="Text"
            ),
        ),
    ]
